package com.inventory.model;

/**
 * Represents a product that is stored in inventory.
 * This is a simple POJO (Plain Old Java Object) using OOP concepts
 * like encapsulation - fields are private, accessed through getters/setters.
 */
public class Product {

    private int id;
    private String name;
    private double price;
    private int quantity;

    // Empty constructor - needed when creating an object before setting values
    public Product() {
    }

    // Constructor used when creating a new product (id is auto-generated by DB)
    public Product(String name, double price, int quantity) {
        this.name = name;
        this.price = price;
        this.quantity = quantity;
    }

    // Constructor used when reading a product back from the database
    public Product(int id, String name, double price, int quantity) {
        this.id = id;
        this.name = name;
        this.price = price;
        this.quantity = quantity;
    }

    // Getters and setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
}
